apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dmitrii-popkov-spring-exercise.fullname" . }}
  labels:
    {{- include "dmitrii-popkov-spring-exercise.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "dmitrii-popkov-spring-exercise.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "dmitrii-popkov-spring-exercise.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dmitrii-popkov-spring-exercise.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
          - name: init-dmitrii-popkov-spring-exercise-db
            image: busybox
            command: ["sh", "-c", "while ! nc -w 1 dmitrii-popkov-spring-exercise-db 5432 </dev/null; do echo waiting for dmitrii-popkov-spring-exercise-db; sleep 10; done;"]
      containers:
        - name: dmitrii-popkov-spring-exercise
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_DATABASE
              value: dmitrii-popkov-spring-exercise-db
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "admin"
          {{- if .Values.framework }}
          {{- if eq .Values.framework "operator-sdk" }}
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          {{- end}}
          {{- end}}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
{{- if .Values.framework }}
{{- if ne .Values.framework "operator-sdk" }}
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
{{- end}}
{{- end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 10 }}
      {{- end }}
