apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: dmitrii-popkov-spring-exercise-db
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: "1Gi"
    storageClassName: gp2
